[package]
name = "memory-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
ratatui = "0.25.0"
better-panic = "0.3.0"
once_cell = "1.19.0"
rand = "0.8.5"